#!/bin/bash
source output.txt
printf "
$1
$1$1
$1$1$ad
$1$1$soyad
$1$1$sehir
$1$1$memleket
$1$1$splaka
$1$1$mplaka
$1$1$yil
$1$1$dogumyil
$1$1$dogumay
$1$1$dogumgun
$1$1$takim
$1$1$ktakim
$1$1$tyil

$1$ad
$1$ad$ad
$1$ad$soyad
$1$ad$sehir
$1$ad$memleket
$1$ad$splaka
$1$ad$mplaka
$1$ad$yil
$1$ad$dogumyil
$1$ad$dogumay
$1$ad$dogumgun
$1$ad$takim
$1$ad$ktakim
$1$ad$tyil

$1$soyad
$1$soyad$ad
$1$soyad$soyad
$1$soyad$sehir
$1$soyad$memleket
$1$soyad$splaka
$1$soyad$mplaka
$1$soyad$yil
$1$soyad$dogumyil
$1$soyad$dogumay
$1$soyad$dogumgun
$1$soyad$takim
$1$soyad$ktakim
$1$soyad$tyil

$1$sehir
$1$sehir$ad
$1$sehir$soyad
$1$sehir$sehir
$1$sehir$memleket
$1$sehir$splaka
$1$sehir$mplaka
$1$sehir$yil
$1$sehir$dogumyil
$1$sehir$dogumay
$1$sehir$dogumgun
$1$sehir$takim
$1$sehir$ktakim
$1$sehir$tyil

$1$memleket
$1$memleket$ad
$1$memleket$soyad
$1$memleket$sehir
$1$memleket$memleket
$1$memleket$splaka
$1$memleket$mplaka
$1$memleket$yil
$1$memleket$dogumyil
$1$memleket$dogumay
$1$memleket$dogumgun
$1$memleket$takim
$1$memleket$ktakim
$1$memleket$tyil

$1$splaka
$1$splaka$ad
$1$splaka$soyad
$1$splaka$sehir
$1$splaka$memleket
$1$splaka$splaka
$1$splaka$mplaka
$1$splaka$yil
$1$splaka$dogumyil
$1$splaka$dogumay
$1$splaka$dogumgun
$1$splaka$takim
$1$splaka$ktakim
$1$splaka$tyil

$1$mplaka
$1$mplaka$ad
$1$mplaka$soyad
$1$mplaka$sehir
$1$mplaka$memleket
$1$mplaka$splaka
$1$mplaka$mplaka
$1$mplaka$yil
$1$mplaka$dogumyil
$1$mplaka$dogumay
$1$mplaka$dogumgun
$1$mplaka$takim
$1$mplaka$ktakim
$1$mplaka$tyil

$1$yil
$1$yil$ad
$1$yil$soyad
$1$yil$sehir
$1$yil$memleket
$1$yil$splaka
$1$yil$mplaka
$1$yil$yil
$1$yil$dogumyil
$1$yil$dogumay
$1$yil$dogumgun
$1$yil$takim
$1$yil$ktakim
$1$yil$tyil

$1$dogumyil
$1$dogumyil$ad
$1$dogumyil$soyad
$1$dogumyil$sehir
$1$dogumyil$memleket
$1$dogumyil$splaka
$1$dogumyil$mplaka
$1$dogumyil$yil
$1$dogumyil$dogumyil
$1$dogumyil$dogumay
$1$dogumyil$dogumgun
$1$dogumyil$takim
$1$dogumyil$ktakim
$1$dogumyil$tyil

$1$dogumay
$1$dogumay$ad
$1$dogumay$soyad
$1$dogumay$sehir
$1$dogumay$memleket
$1$dogumay$splaka
$1$dogumay$mplaka
$1$dogumay$yil
$1$dogumay$dogumyil
$1$dogumay$dogumay
$1$dogumay$dogumgun
$1$dogumay$takim
$1$dogumay$ktakim
$1$dogumay$tyil

$1$dogumgun
$1$dogumgun$ad
$1$dogumgun$soyad
$1$dogumgun$sehir
$1$dogumgun$memleket
$1$dogumgun$splaka
$1$dogumgun$mplaka
$1$dogumgun$yil
$1$dogumgun$dogumyil
$1$dogumgun$dogumay
$1$dogumgun$dogumgun
$1$dogumgun$takim
$1$dogumgun$ktakim
$1$dogumgun$tyil

$1$takim
$1$takim$ad
$1$takim$soyad
$1$takim$sehir
$1$takim$memleket
$1$takim$splaka
$1$takim$mplaka
$1$takim$yil
$1$takim$dogumyil
$1$takim$dogumay
$1$takim$dogumgun
$1$takim$takim
$1$takim$ktakim
$1$takim$tyil

$1$ktakim
$1$ktakim$ad
$1$ktakim$soyad
$1$ktakim$sehir
$1$ktakim$memleket
$1$ktakim$splaka
$1$ktakim$mplaka
$1$ktakim$yil
$1$ktakim$dogumyil
$1$ktakim$dogumay
$1$ktakim$dogumgun
$1$ktakim$takim
$1$ktakim$ktakim
$1$ktakim$tyil

$1$tyil
$1$tyil$ad
$1$tyil$soyad
$1$tyil$sehir
$1$tyil$memleket
$1$tyil$splaka
$1$tyil$mplaka
$1$tyil$yil
$1$tyil$dogumyil
$1$tyil$dogumay
$1$tyil$dogumgun
$1$tyil$takim
$1$tyil$ktakim
$1$tyil$tyil" >> ../wordlist.txt



